const constants = {
  ADD_TRANSACTION: "ADD_TRANSACTION",
  GET_TRANSACTIONS: "GET_TRANSACTIONS",
  DELETE_TRANSACTION: "DELETE_TRANSACTION",
  TRANSACTION_ERROR: "TRANSACTION_ERROR",
};

export default constants;
